---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "walletd"
  namespace: REPLACE_NAMESPACE
  annotations:
    kubernetes.io/ingress.class: "traefik"
    external-dns.alpha.kubernetes.io/hostname: 1.walletd.REPLACE_DOMAIN_SUFFIX
    external-dns.alpha.kubernetes.io/target: "router.REPLACE_DOMAIN_SUFFIX."
  labels:
    app: walletd
spec:
  rules:
  - host: "1.walletd.REPLACE_DOMAIN_SUFFIX"
    http:
      paths:
      - backend:
          serviceName: "walletd-svc"
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: walletd-svc
  namespace: REPLACE_NAMESPACE 
  labels:
    name: walletd-svc
spec:
  type: ClusterIP 
  ports:
    - port: 80 
      protocol: TCP
      targetPort: 8088
  selector:
    app: walletd
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: walletd
  name: walletd
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  selector:
    matchLabels:
      app: walletd
  template:
    metadata:
      labels:
        app: walletd
    spec:
      containers:
      - name: walleted
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8088 
        command: ["/go/bin/walletd"]
        args: ["-conf-dir=/data/config/stage"]
