stages:
  - build
  - deploy

variables:

  #GLOBAL
  IMAGE_NAME: walletd

  #STAGE
  ACCOUNT_ID_STAGE: 063193438988
  AWS_REGION_STAGE: "us-west-2"
  DOCKER_REPO_STAGE: $ACCOUNT_ID_STAGE.dkr.ecr.$AWS_REGION_STAGE.amazonaws.com/$IMAGE_NAME
  APP_REPLICAS_STAGE: "1"
  ECRLOGIN_STAGE: "aws ecr get-login --registry-ids $ACCOUNT_ID_STAGE --region $AWS_REGION_STAGE --no-include-email"



#STAGE
Build stage Docker image:
  stage: build
  tags:
    - stage
  script:
    - docker build -t $IMAGE_NAME:$CI_BUILD_REF -f Dockerfile .
    - DOCKER_LOGIN_TO_STAGE_REPO=`$ECRLOGIN_STAGE`
    - docker tag $IMAGE_NAME:$CI_BUILD_REF $DOCKER_REPO_STAGE:$CI_BUILD_REF
    - $DOCKER_LOGIN_TO_STAGE_REPO && docker push $DOCKER_REPO_STAGE:$CI_BUILD_REF

  only:
    - master

Deploy to stage cluster:
  stage: deploy
  tags:
    - stage
  script:
    - apk add bash
    - export K8S_API_VERSION=$STAGE_K8_API_VERSION
    - .k8/scripts/deploy-yamls-on-k8s.sh $DOCKER_REPO_STAGE $CI_BUILD_REF blockchain $APP_REPLICAS_STAGE stage admin-stage stage.blox.io $K8S_API_VERSION
  only:
    - master
