version: '3'

services:
  bloxapp_walletd:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/config/local:/data/config/stage
    command: "/go/bin/walletd -conf-dir=/data/config/stage"
#    command: "/bin/sh"
    ports:
      - "8088:8088"
    restart: on-failure
